### ISSUE TITLE
uTool 3.2.7 shows no pic

### ISSUE THREAD

**Issue by hakeen980** [Vzense/UTool#1]
Tool opens, connected OK, but no pics to see. Neither RGB nor IR etc.
Firewall for uTool.exe is allowed, no blocking.. Same for Frameviewer

Win7, DCAM710.
FW= DCAM710_c086_pc_sv0.01_R6_20181120_b44

![uTool connected but no pic](https://user-images.githubusercontent.com/49987809/106360205-8283b780-6317-11eb-8db0-75f2a263a1e1.JPG)
![FwallOK](https://user-images.githubusercontent.com/49987809/106360207-84e61180-6317-11eb-9883-e7ecd4d4526a.JPG)

...

**Comment by hakeen980** [comment]
uTool 3.0.0.8 functions.

**Comment by peter-vzense** [comment]
firmware version is very low, please upgrade the firmware first. Thank you. @hakeen980
